#!/bin/bash
if [[ $1 == 'ec2' && $2 == 'describe-instances' ]]; then
  if [[ $5 == '--query' && $6 == "'Reservations[0].Instances[0].State.Name'" ]]; then
    echo running
  elif [[ $5 == '--query' && $6 == "'Reservations[0].Instances[0].PublicIpAddress'" ]]; then
    echo 203.0.113.10
  fi
  exit 0
elif [[ $1 == 'ec2' && $2 == 'start-instances' ]]; then
  exit 0
fi
exit 0
