name: Deploy EC2 Environment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID || env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY || env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || env.AWS_REGION }}
      - run: npm ci
      - run: npx cdk deploy --require-approval never
      - name: Set ALLOWED_IP (optionally)
        run: echo "ALLOWED_IP=203.0.113.1/32" >> $GITHUB_ENV
        if: false # Enable this step only if you need to restrict access to a specific IP address
      - name: Set SPOT_MAX_PRICE (optionally)
        run: echo "SPOT_MAX_PRICE=0.05" >> $GITHUB_ENV
        if: false # 必要な場合のみ有効化
